title: Jia Jianbing's Homepage
page-top-title: Jia Jianbing
top-section-bg-text: Personal Introduction
home-subtitle: Jia Jianbing&ensp;|&ensp;贾建兵
copyright-text: '&copy; Jia Jianbing 2024-2023. All Rights Reserved.'
